apiVersion: apps/v1
kind: Deployment
metadata:
  name: goproductsapi
spec:
  selector:
    matchLabels:
      app: goproductsapi
  template:
    metadata:
      labels:
        app: goproductsapi
    spec:
      containers:
        - name: goproductsapi
          image: nilanjanb3/goproductsapi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: goproductsapi
spec:
  selector:
    app: goproductsapi
  ports:
    - port: 80
      targetPort: 80
